---
title: "Data Exporation"
output: html_document
date: "2023-06-21"
---

```{r Setup}

library(tidyverse)
library(here)
library(lubridate)
library(maps)
library(modelr)

city_day_data <- read_csv("city_day_agg_cleaned.csv.gz")

country_day_data <- read_csv("country_day_agg_cleaned.csv.gz")

city_loc_data <- read_csv("openaq_cities.csv")

city_pop_dens <- read_csv("pop_dens_cities.csv") %>% 
  select(city_id, countryCode, mean) %>% 
  rename(pop_density_mean=mean)

country_pop_dens <- read_csv("pop_dens_country.csv") %>% 
  select(city_id, countryCode, mean) %>% 
  rename(pop_density_mean=mean)
```

Looking at the data we have two tables with the following features:

#### city_day_data (Features)

- country
- countryCode
- city_id
- date
- parameter
- mean

#### country_data_data (Features)

- countryCode
- date
- parameter
- mean

### Notes

POPULATION WEIGHTED MEAN!

```{r Data Preparation}

wider_city_data <- city_day_data %>% 
  pivot_wider(names_from=parameter, values_from=mean) %>% 
  select(-c(no2, o3)) %>% 
  na.omit() %>% 
  rename(city_average_pm25=pm25)

wider_country_data <- country_day_data %>% 
  pivot_wider(names_from=parameter, values_from=mean) %>% 
  select(-c(no2, o3)) %>% 
  na.omit() %>% 
  rename(country_average_pm25=pm25)

combined_city_country <- wider_city_data %>% 
  left_join(wider_country_data, by=c("countryCode", "date"))

data_from_period_3_year <- combined_city_country %>% 
  filter(year(date) < 2020, month(date) >= 1, month(date) <= 5) %>% 
  group_by(countryCode, city_id) %>% 
  summarize(average_pm25_3_year=mean(city_average_pm25)) 
  
data_from_2020 <- combined_city_country %>% 
  filter(year(date) == 2020, month(date) >= 1, month(date) <= 5) %>% 
  group_by(countryCode, city_id) %>% 
  summarize(average_pm25_2020=mean(city_average_pm25)) 

combined_averages <- data_from_2020 %>% 
  inner_join(data_from_period_3_year, by=c("city_id", "countryCode"))

combined_city_country %>%  
  filter(month(date) >= 1, month(date) <= 5, countryCode %in% common_countries$countryCode) %>% 
  mutate(year_period=as.factor(ifelse(year(date) < 2020, "3-year", "2020"))) %>% 
  group_by(countryCode, city_id, year_period) %>% 
  summarize(mean_pm25=mean(city_average_pm25)) %>% 
  group_by(year_period) %>% 
  mutate(median_2020=median(mean_pm25)) %>% 
  ggplot(aes(x=mean_pm25, color=year_period)) + 
  geom_density(aes(fill=year_period, alpha=0.5)) +
  geom_vline(aes(xintercept = median_2020, color=year_period))

combined_averages %>% 
  pivot_longer(cols=c("average_pm25_2020", "average_pm25_3_year"), values_to="average_pm25") %>% 
  group_by(name) %>% 
  mutate(median=median(average_pm25)) %>% 
  ggplot(aes(x=average_pm25, color=name)) + 
  geom_density(aes(fill=name, alpha=0.5)) +
  geom_vline(aes(xintercept = median, color=name))

```

### Map graph

```{r map}

rel_changes <- combined_averages %>% 
  mutate(rel_change = ((average_pm25_2020 - average_pm25_3_year)/average_pm25_3_year)*100) %>% 
  left_join(city_loc_data) %>% 
  filter(rel_change > -30, rel_change < 30)

combined_averages %>% 
  mutate(rel_change = ((average_pm25_2020 - average_pm25_3_year)/average_pm25_3_year)*100) %>% 
  left_join(city_loc_data) %>% 
  ggplot(aes(rel_change)) +
  geom_histogram()

max(rel_changes$rel_change)
min(rel_changes$rel_change)

ggplot(map_data("world"), aes(long, lat)) + 
  geom_polygon(aes(group=group), fill="lightgray", color="white") +
  geom_point(data=rel_changes, aes(x=Lon,y=Lat, color=rel_change), shape=1) +
  coord_cartesian(xlim=c(-120, 125), ylim=c(-50,75))
```

### Model creation 

```{r Model Creation}

country_locs <- read_csv("countries_codes_and_coordinates.csv") %>% 
  rename(lat="Latitude (average)", long="Longitude (average)", countryCode="Alpha-3 code")

country_data <- wider_country_data %>% 
  inner_join(country_locs, by = c("countryCode"="Alpha-3 code")) %>% 
  group_by(countryCode, date) %>% 
  summarize(pm25=country_average_pm25[1], lat=lat[1], long=long[1]) %>% 
  mutate(month=as.factor(month(date, label=TRUE)), is_weekend=weekdays(date) %in% c("Saturday", "Sunday"))

country_data_2020 <- country_data %>% 
  filter(year(date) == 2020, !(countryCode %in% c("AUT", "GRC", "HUN", "ISL", "ITA")))

country_data_17_19 <- country_data %>% 
  filter(year(date) < 2020)

lm <- lm(pm25 ~ lat*month +long*month + is_weekend*lat + is_weekend*long + countryCode,data=country_data_17_19)
preds <- predict(lm, newdata = country_data_2020, se.fit = T)
summary(lm)
country_data_2020$pred = preds$fit
country_data_2020$se = preds$se.fit

1-mean((country_data_2020$pm25 -country_data_2020$pred)^2)/var(country_data_2020$pm25)
sqrt(mean((country_data_2020$pm25 -country_data_2020$pred)^2))

country_data_2020 %>% 
  group_by(countryCode) %>% 
  summarize(pred_mean = mean(pred), actual_mean = mean(pm25), mean_se=mean(se)*1.96) %>% 
  mutate(abs_diff=pred_mean-actual_mean, rel_change=(actual_mean-pred_mean)/actual_mean * 100) %>% 
  filter(rel_change > -150) %>% 
  left_join(country_locs, by="countryCode") %>% 
  ggplot(aes(x=Country, y=rel_change, color=rel_change)) +
  geom_errorbar(aes(ymin=rel_change-1.96*mean_se, ymax=rel_change+1.96*mean_se)) +
  geom_point() +
  geom_hline(yintercept=0, linetype="dotdash") +
  coord_flip()

```

